version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-demo:/data/db

volumes:
  mongo-data-demo:
